### ISSUE TITLE
copilot comparision

### ISSUE THREAD

**Issue by etnt** [mbj4668/gen-md-erl#1]
Hi there!

Loved your awk script :-)

I just made a fun experiment asking Github Copilot to generate an awk script
based on your description in the code comments.
Have a look at the example output: https://github.com/etnt/erl_md/tree/main/example_output

Just for fun, this issue can be closed.

Cheers, Tobbe

**Comment by mbj4668** [comment]
Haha, nice!  But it didn't do the links to the types ;-)
